# Generated by Django 5.1.2 on 2024-10-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ПОльзователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
