# Generated by Django 5.1.2 on 2024-10-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=7, verbose_name='Тип транзакции')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
