# Generated by Django 5.1.2 on 2024-10-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_transactions', '0001_initial'),
        ('users', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user', verbose_name='Пользователь (ID)'),
        ),
    ]
