# Generated by Django 5.1.2 on 2024-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_transactions', '0004_reportsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsresult',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Отправить на email'),
        ),
    ]
