# Generated by Django 5.1.2 on 2024-10-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_transactions', '0005_reportsresult_send_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsresult',
            options={'verbose_name': 'Отчет по пользователю', 'verbose_name_plural': 'Отчеты по пользователю'},
        ),
        migrations.AlterModelTable(
            name='reportsresult',
            table='reports_result',
        ),
    ]
